var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/app/casos/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__d9ae52d5._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_ac25c82c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3db39f03._.js")
R.c("server/chunks/ssr/[root-of-the-server]__85eeb158._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_layout_tsx_271801d7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_5e4408b8._.js")
R.c("server/chunks/ssr/_next-internal_server_app_app_casos_page_actions_837353b8.js")
R.m(48487)
module.exports=R.m(48487).exports
