var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(site)/en/methods/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__fa8a0192._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_9dfdce7d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3db39f03._.js")
R.c("server/chunks/ssr/[root-of-the-server]__85eeb158._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_layout_tsx_271801d7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_70078619._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(site)_en_methods_page_actions_ab93be06.js")
R.m(29869)
module.exports=R.m(29869).exports
