// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(site)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../app/(site)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../app/(site)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/en/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/en/about">> = Specific
  const handler = {} as typeof import("../../../app/(site)/en/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/en/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/en/contact">> = Specific
  const handler = {} as typeof import("../../../app/(site)/en/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/en/methods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/en/methods">> = Specific
  const handler = {} as typeof import("../../../app/(site)/en/methods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/en/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/en">> = Specific
  const handler = {} as typeof import("../../../app/(site)/en/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/en/product/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/en/product">> = Specific
  const handler = {} as typeof import("../../../app/(site)/en/product/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/methods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/methods">> = Specific
  const handler = {} as typeof import("../../../app/(site)/methods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(site)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/(site)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/product/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product">> = Specific
  const handler = {} as typeof import("../../../app/(site)/product/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/pt/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pt/about">> = Specific
  const handler = {} as typeof import("../../../app/(site)/pt/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/pt/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pt/contact">> = Specific
  const handler = {} as typeof import("../../../app/(site)/pt/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/pt/methods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pt/methods">> = Specific
  const handler = {} as typeof import("../../../app/(site)/pt/methods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/pt/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pt">> = Specific
  const handler = {} as typeof import("../../../app/(site)/pt/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(site)/pt/product/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pt/product">> = Specific
  const handler = {} as typeof import("../../../app/(site)/pt/product/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/casos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/casos">> = Specific
  const handler = {} as typeof import("../../../app/app/casos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/finance">> = Specific
  const handler = {} as typeof import("../../../app/app/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/imoveis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/imoveis">> = Specific
  const handler = {} as typeof import("../../../app/app/imoveis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/macro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/macro">> = Specific
  const handler = {} as typeof import("../../../app/app/macro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/metodologia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/metodologia">> = Specific
  const handler = {} as typeof import("../../../app/app/metodologia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/real-estate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/real-estate">> = Specific
  const handler = {} as typeof import("../../../app/app/real-estate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/setores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/setores">> = Specific
  const handler = {} as typeof import("../../../app/app/setores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/sobre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/sobre">> = Specific
  const handler = {} as typeof import("../../../app/app/sobre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/assets/[asset]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/[asset]">> = Specific
  const handler = {} as typeof import("../../../app/api/assets/[asset]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets">> = Specific
  const handler = {} as typeof import("../../../app/api/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/overview">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/figures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/figures">> = Specific
  const handler = {} as typeof import("../../../app/api/figures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/files/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/api/files/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/graph/backtest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/backtest">> = Specific
  const handler = {} as typeof import("../../../app/api/graph/backtest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/graph/hypertest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/hypertest">> = Specific
  const handler = {} as typeof import("../../../app/api/graph/hypertest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/graph/official/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/official">> = Specific
  const handler = {} as typeof import("../../../app/api/graph/official/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/graph/regimes-batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/regimes-batch">> = Specific
  const handler = {} as typeof import("../../../app/api/graph/regimes-batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/graph/regimes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/regimes">> = Specific
  const handler = {} as typeof import("../../../app/api/graph/regimes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/graph/sanity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/sanity">> = Specific
  const handler = {} as typeof import("../../../app/api/graph/sanity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/graph/sector/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/sector">> = Specific
  const handler = {} as typeof import("../../../app/api/graph/sector/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/graph/series-batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/series-batch">> = Specific
  const handler = {} as typeof import("../../../app/api/graph/series-batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/graph/universe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/universe">> = Specific
  const handler = {} as typeof import("../../../app/api/graph/universe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/graph/validation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/validation">> = Specific
  const handler = {} as typeof import("../../../app/api/graph/validation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history">> = Specific
  const handler = {} as typeof import("../../../app/api/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/index/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/index">> = Specific
  const handler = {} as typeof import("../../../app/api/index/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/latest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/latest">> = Specific
  const handler = {} as typeof import("../../../app/api/latest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/methodology/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/methodology">> = Specific
  const handler = {} as typeof import("../../../app/api/methodology/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/overview">> = Specific
  const handler = {} as typeof import("../../../app/api/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/realestate/series/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/realestate/series">> = Specific
  const handler = {} as typeof import("../../../app/api/realestate/series/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/realestate/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/realestate/summary">> = Specific
  const handler = {} as typeof import("../../../app/api/realestate/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/regime/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/regime">> = Specific
  const handler = {} as typeof import("../../../app/api/regime/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/risk-truth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/risk-truth">> = Specific
  const handler = {} as typeof import("../../../app/api/risk-truth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/run/latest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/run/latest">> = Specific
  const handler = {} as typeof import("../../../app/api/run/latest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs">> = Specific
  const handler = {} as typeof import("../../../app/api/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../../app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(site)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(site)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
