// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/app/casos" | "/app/dashboard" | "/app/finance" | "/app/imoveis" | "/app/macro" | "/app/metodologia" | "/app/real-estate" | "/app/setores" | "/app/sobre" | "/contact" | "/en" | "/en/about" | "/en/contact" | "/en/methods" | "/en/product" | "/methods" | "/privacy" | "/product" | "/pt" | "/pt/about" | "/pt/contact" | "/pt/methods" | "/pt/product"
type AppRouteHandlerRoutes = "/api/assets" | "/api/assets/[asset]" | "/api/dashboard/overview" | "/api/figures" | "/api/files/[...path]" | "/api/graph/backtest" | "/api/graph/hypertest" | "/api/graph/official" | "/api/graph/regimes" | "/api/graph/regimes-batch" | "/api/graph/sanity" | "/api/graph/sector" | "/api/graph/series-batch" | "/api/graph/universe" | "/api/graph/validation" | "/api/history" | "/api/index" | "/api/latest" | "/api/methodology" | "/api/overview" | "/api/realestate/asset" | "/api/realestate/series" | "/api/realestate/summary" | "/api/regime" | "/api/risk-truth" | "/api/run/latest" | "/api/runs" | "/api/search"
type PageRoutes = never
type LayoutRoutes = "/" | "/app"
type RedirectRoutes = "/api-docs" | "/app/imoveis" | "/ativos" | "/benchmark" | "/dashboard" | "/forecast-check" | "/setores" | "/simulador" | "/sobre"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/api-docs": {}
  "/api/assets": {}
  "/api/assets/[asset]": { "asset": string; }
  "/api/dashboard/overview": {}
  "/api/figures": {}
  "/api/files/[...path]": { "path": string[]; }
  "/api/graph/backtest": {}
  "/api/graph/hypertest": {}
  "/api/graph/official": {}
  "/api/graph/regimes": {}
  "/api/graph/regimes-batch": {}
  "/api/graph/sanity": {}
  "/api/graph/sector": {}
  "/api/graph/series-batch": {}
  "/api/graph/universe": {}
  "/api/graph/validation": {}
  "/api/history": {}
  "/api/index": {}
  "/api/latest": {}
  "/api/methodology": {}
  "/api/overview": {}
  "/api/realestate/asset": {}
  "/api/realestate/series": {}
  "/api/realestate/summary": {}
  "/api/regime": {}
  "/api/risk-truth": {}
  "/api/run/latest": {}
  "/api/runs": {}
  "/api/search": {}
  "/app": {}
  "/app/casos": {}
  "/app/dashboard": {}
  "/app/finance": {}
  "/app/imoveis": {}
  "/app/macro": {}
  "/app/metodologia": {}
  "/app/real-estate": {}
  "/app/setores": {}
  "/app/sobre": {}
  "/ativos": {}
  "/benchmark": {}
  "/contact": {}
  "/dashboard": {}
  "/en": {}
  "/en/about": {}
  "/en/contact": {}
  "/en/methods": {}
  "/en/product": {}
  "/forecast-check": {}
  "/methods": {}
  "/privacy": {}
  "/product": {}
  "/pt": {}
  "/pt/about": {}
  "/pt/contact": {}
  "/pt/methods": {}
  "/pt/product": {}
  "/setores": {}
  "/simulador": {}
  "/sobre": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
