var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/app/dashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__240c7ea1._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_9f021ce2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3db39f03._.js")
R.c("server/chunks/ssr/[root-of-the-server]__85eeb158._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_layout_tsx_271801d7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_5e4408b8._.js")
R.c("server/chunks/ssr/_next-internal_server_app_app_dashboard_page_actions_579f28bd.js")
R.m(38981)
module.exports=R.m(38981).exports
