var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/app/sobre/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__62c1af5c._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_4488c30b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3db39f03._.js")
R.c("server/chunks/ssr/[root-of-the-server]__85eeb158._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_layout_tsx_271801d7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_5e4408b8._.js")
R.c("server/chunks/ssr/_next-internal_server_app_app_sobre_page_actions_acc75f0e.js")
R.m(8575)
module.exports=R.m(8575).exports
