export const assetNames: Record<string, string> = {
  "SPY": "SPDR S&P 500 ETF",
  "QQQ": "Invesco QQQ (Nasdaq 100)",
  "DIA": "SPDR Dow Jones Industrial",
  "IWM": "iShares Russell 2000",
  "VTI": "Vanguard Total Stock Market",
  "VT": "Vanguard Total World Stock",
  "RSP": "Invesco S&P 500 Equal Weight",
  "XLF": "Financial Select Sector",
  "XLE": "Energy Select Sector",
  "XLI": "Industrial Select Sector",
  "XLK": "Technology Select Sector",
  "XLP": "Consumer Staples Select Sector",
  "XLY": "Consumer Discretionary Select Sector",
  "XLV": "Health Care Select Sector",
  "XLU": "Utilities Select Sector",
  "XLRE": "Real Estate Select Sector",
  "XLB": "Materials Select Sector",
  "XOP": "SPDR Oil & Gas Exploration",
  "GLD": "SPDR Gold Shares",
  "SLV": "iShares Silver Trust",
  "USO": "United States Oil Fund",
  "DBC": "Invesco DB Commodity Index",
  "DBA": "Invesco DB Agriculture Fund",
  "TLT": "iShares 20+ Year Treasury",
  "IEF": "iShares 7-10 Year Treasury",
  "SHY": "iShares 1-3 Year Treasury",
  "TIP": "iShares TIPS Bond ETF",
  "LQD": "iShares Investment Grade Corp",
  "HYG": "iShares High Yield Corp",
  "UUP": "Invesco US Dollar Index",
  "FXE": "Invesco Euro Currency",
  "FXY": "Invesco Japanese Yen",
  "VIX": "CBOE Volatility Index",
  "^VIX": "CBOE Volatility Index",
  "BTC-USD": "Bitcoin",
  "ETH-USD": "Ethereum",
  "EWJ": "iShares MSCI Japan",
  "EWZ": "iShares MSCI Brazil",
  "EEM": "iShares MSCI Emerging Markets",
  "EFA": "iShares MSCI EAFE",
};

export function nameForAsset(asset: string) {
  return assetNames[asset] || asset;
}
