export const regionLabels: Record<string, string> = {
  us: "US",
  global: "Global",
  crypto: "Crypto",
  fx: "FX",
  commodities: "Commodities",
};

export const assetRegion: Record<string, string> = {
  SPY: "us",
  QQQ: "us",
  DIA: "us",
  IWM: "us",
  VTI: "us",
  RSP: "us",
  XLF: "us",
  XLE: "us",
  XLK: "us",
  XLP: "us",
  XLV: "us",
  XLU: "us",
  XLY: "us",
  XLB: "us",
  XLRE: "us",
  KRE: "us",
  LQD: "us",
  HYG: "us",
  SHY: "us",
  IEF: "us",
  TLT: "us",
  TIP: "us",
  VIX: "us",
  "^VIX": "us",
  VT: "global",
  EEM: "global",
  EFA: "global",
  EWJ: "global",
  EWZ: "global",
  GLD: "commodities",
  SLV: "commodities",
  USO: "commodities",
  DBA: "commodities",
  DBC: "commodities",
  XOP: "commodities",
  UUP: "fx",
  FXE: "fx",
  FXY: "fx",
  "BTC-USD": "crypto",
  "ETH-USD": "crypto",
};
